blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.allblog ,name = 'blog'),
    path('<int:blog_id>', views.detail , name = 'detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from portfolio import views

# app_name='main'

urlpatterns = [
    path('', views.home ,name = 'home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now=False)
    description = models.TextField()
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='project/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def allblog(request):
    blogs = Blog.objects.order_by('-date')[:6]
    return render(request,'blog/allblog.html',{'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request,'portfolio/home.html',{'projects':projects})

blog/templates/blog/allblog.html
{% extends 'portfolio/main.html' %}
{% block content %}
    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4 text-uppercase">Blog Posts</h1>
        <small class="text-muted">Total Blog{{blogs.count | pluralize}} writtern : {{ blogs.count}}</small>
        <hr class="border-2">
         <!-- Blog Post -->
         {% for blog in blogs %}
        <div class="card mb-4">
            {% if blog.image%}
            <img class="card-img-top" src="{{ blog.image.url }}" alt="Card image cap">
            {% endif %}
            <div class="card-body">
            <h2 class="card-title">{{ blog.title }}</h2>
            <p class="card-text">{{blog.description|truncatechars:100}}</p>
            <a href="{% url 'blog:detail' blog.id%}" class="btn btn-primary">Read More &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Posted on {{ blog.date | date:'d M Y' }}
          </div>
        </div>
    {% endfor %}
    </div>
    
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/main.html' %}
{% block content %}

<div class="row" id="maincontent">

    <!-- Post Content Column -->
    <div class="col">

    <!-- Title -->
    <h1 class="mt-4">{{ blog.title }}</h1>
    <hr>

    <!-- Date/Time -->
    <p>Posted on {{ blog.date|date:'F jS Y' }}</p>

    <hr>

    <!-- Preview Image -->
    {% if blog.image%}
    <img class="img-fluid rounded" src="{{ blog.image.url }}" alt="">
    <hr>
    {% endif %}
    <!-- Post Content -->
    <p class="lead">{{blog.description | safe }}</p>
</div>
{% endblock%}

portfolio/templates/portfolio/home.html
{% extends "portfolio/main.html" %}
{% block content%}
{% load static %}

 <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <h1 class="display-3">A Warm Welcome!</h1>
      <p class="lead">
      I am Aashish Thapa Magar, student of Information Technology.
      </p>
      <a href="{% static 'portfolio/aashishcv.pdf' %}" class="btn btn-primary btn-lg">Get CV</a>
    </header>

    <!-- Project Card -->
    <div class="row text-center">
    {% for project in projects %}
    <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="{{ project.image.url }}" alt="">
          <div class="card-body">
            <h4 class="card-title">{{ project.title }}</h4>
            <p class="card-text">{{ project.description|truncatechars:100 }}</p>
          </div>
          <div class="card-footer">
            <a href="{% url "project.url" %}" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
    </div>
    {% endfor %}
    </div>
{% endblock %}

portfolio/templates/portfolio/main.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Aashish Thapa Magar</title>

  <!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Bootstrap core CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  {% load static %}
  <link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static "portfolio/logo.png" %}">

</head>

<body>
{% load static %}
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand text-uppercase" href="{% url 'home' %}">Aashish Thapa Magar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/aashishcv.pdf' %}">Get CV</a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li> {% endcomment %}
        </ul>
      </div>
    </div>
  </nav>
   <!-- Page Content -->
  <div class="container">

  {% block content %}
  {% endblock  %}

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
     
      <p class="m-0 text-center text-white">Copyright &copy; Aashish Thapa Magar 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>